apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pvName }}
namespace: openlend-qa
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  hostPath:
    path: {{ .Values.storage.path }}

