apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qa-openlend-pvc
namespace: openlend-qa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeName: {{ .Values.storage.pvName }}
  storageClassName: {{ .Values.storage.storageClassName }}

